name: py38
channels:
  - defaults
  - conda-forge
dependencies:
  - arviz
  - astropy
  - black
  - bokeh
  - click
  - colorama
  - cupy
  - dask
  - distributed
  - doit
  - fuzzywuzzy
  - flake8
  - h5py
  - hypothesis
  - ipykernel
  - ipympl
  - ipython
  - ipywidgets
  - jupyterlab
  - line_profiler
  - lmfit
  - markdown
  - matplotlib
  - mpmath
  - nbdime
  - nodejs
  - numba
  - numpy
  - numpydoc
  - pandas
  - pillow
  - pip
  - pre_commit
  - pyaudio
  - pudb
  - pymc3
  - pynvim
  - pytest
  - pytest-cov
  - python=3.8
  - pyvista
  - requests
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - sphinx
  - sphinx-automodapi
  - sphinx-gallery
  - sphinx_rtd_theme
  - sympy
  - theano
  - towncrier
  - tox
  - tox-conda
  - tqdm
  - widgetsnbextension
  - xarray
  - pip:
    - pytest-pudb
    - todoist-python
    - togglCli
    - pubs
    - flake8-docstrings

