name: base
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - colorama
  - black
  - pyvista
  - numpy
  - scipy
  - numba
  - pytest
  - tqdm
  - astropy
  - xarray
  - dask
  - hypothesis
  - bokeh
  - matplotlib
  - pymc3
  - seaborn
  - jupyterlab
  - fenics
  - pandas
  - ipywidgets
  - click
  - doit
  - h5py
  - lmfit
  - pillow
  - pudb
  - pynvim
  - pytest-cov
  - requests
  - scikit-image
  - shapely
  - sympy
  - tox
  - tox-conda
  - ipympl
  - nodejs
  - widgetsnbextension
  - itkwidgets
  - pip
  - arviz
  - ipython
  - line_profiler
  - mpmath
  - sphinx
  - towncrier
  - sphinx-gallery
  - sphinx-automodapi
  - sphinx_rtd_theme
  - numpydoc
  - flake8
  - pre_commit
  - nbdime
  - pip:
    - pytest-pudb
    - todoist-python
    - togglCli
    - pubs
    - flake8-docstrings

