wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [29, 29, 32, 32, 32, 35]
    rows: [10, 10, 10, 7]
  refreshInterval: 1
  mods:
    # put gcal here
    gcal:
      colors:
        title: "red"
        eventTime: "lightblue"
        highlights:
          - ['Paulina', 'magenta']
          - ['Plan Pauliny na PW', 'magenta']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "stanczakdominik@gmail.com"
      enabled: true
      eventCount: 15
      hourFormat: "24"
      multiCalendar: false
      position:
        top: 0
        left: 0
        height: 4
        width: 2
      refreshInterval: 300
      secretFile: "~/.config/wtf/credentials.json"
      showDeclined: true
      timezone: "Europe/Warsaw"
      withLocation: true
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 3
        left: 4
        height: 1
        width: 2
      refreshInterval: 1
    git:
      commitCount: 5
      commitFormat: "[forestgreen]%h [grey]%cd [white]%s [grey]%an[white]"
      dateFormat: "%H:%M %d %b %y"
      enabled: true
      position:
        top: 0
        left: 2
        height: 2
        width: 2
      refreshInterval: 8
      repositories:
      - "/home/dominik/Code/dotfiles/"
      - "/home/dominik/Code/PlasmaPy/"
      - "/home/dominik/Writing/Magisterium/"
      - "/home/dominik/Writing/blog/"
      - "/home/dominik/.pubs"
    # github:
    #   apiKey: ""
    #   baseURL: ""
    #   customQueries:
    #     othersPRs:
    #       title: "Others Pull Requests"
    #       filter: "is:open is:pr -author:wtfutil"
    #   enabled: true
    #   enableStatus: true
    #   position:
    #     top: 2
    #     left: 3
    #     height: 2
    #     width: 2
    #   refreshInterval: 300
    #   repositories:
    #     - "PlasmaPy/PlasmaPy"
    #   uploadURL: ""
    #   username: "stanczakdominik"
    todoist:
      enabled: true
      position:
        top: 0
        left: 4
        height: 3
        width: 2
      projects:
        - 2216038565
        - 2216098300
        - 2216038567
        - 2216038571
        - 2218593242
        - 2216038576
        - 2218141002

      refreshInterval: 3600
    spotify:
      enabled: true
      colors:
        label: "green"
        text: "white"
      position:
        top: 3
        left: 2
        height: 1
        width: 2
      refreshInterval: 0
    # workhours:
    #   args: [""]
    #   cmd: "workhours.py"
    #   enabled: true
    #   position:
    #     top: 2
    #     left: 2
    #     height: 1
    #     width: 1
    #   refreshInterval: 30
    #   type: cmdrunner
    prettyweather:
      enabled: true
      city: "warsaw"
      position:
        top: 2
        left: 3
        height: 1
        width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
